### ISSUE TITLE
polling interval from GitHub?

### ISSUE THREAD

**Issue by rvoitenko** [promhippie/github_exporter#152]
Hi,

thank you for this awesome tool first of all.
I'm using it for monitoring Github Actions minutes monitoring.

But what I see is that github_exporter does a lot of requests to GitHub with the token I provided to it. Around 600-700 per hour.
I don't need my data so often, my scrape_interval is 5m.
Is it possible to configure polling interval to decrease the amount of API requests towards GitHub?

**Comment by tboerger** [comment]
The github api only gets requested if you call the metrics, so just increase the scrape interval to the time window you are comfortable with.

**Comment by luciano-buono** [comment]
Hi, @tboerger. Commenting here in order not to create an issue of the same topic.

Can you help me defining the right values for the arguments in order to avoid the timeouts/rateLimits?

```yaml
      extraEnvVariables:
        GITHUB_EXPORTER_ORGS: XX
        #~1000 repos, 300 of them have workflows
        GITHUB_EXPORTER_REPOS: XX/*
        # Information about Organization
        GITHUB_EXPORTER_COLLECTOR_BILLING: true
        # This admin stats are only for enterprise accounts
        GITHUB_EXPORTER_COLLECTOR_ADMIN: false
        # Information about repos. Not needed
        GITHUB_EXPORTER_COLLECTOR_REPOS: false
        # Information about orgs and repos runners. If they are busy or idle. Not needed
        GITHUB_EXPORTER_COLLECTOR_RUNNERS: false
        # Information about workflows. Check timeouts
        GITHUB_EXPORTER_COLLECTOR_WORKFLOWS: true
        # Needed to avoid context deadline exceeded errors in collector
        GITHUB_EXPORTER_REQUEST_TIMEOUT: 10m
        GITHUB_EXPORTER_PER_PAGE: 200
        GITHUB_EXPORTER_WEB_TIMEOUT: 10m
        # Log level
        GITHUB_EXPORTER_LOG_LEVEL: debug
```

Prometheus scrape config for this exporter:
```yaml
    - job_name: prometheus-promhippie-github-exporter
      metrics_path: /metrics
      scrape_interval: 1h
      scrape_timeout: 10m
      static_configs:
        - targets:
          - prometheus-promhippie-github-exporter:9504
```

With this config, I'm not seeing rateLimiting by Github, however I have this log 
`2023/09/07 12:34:16 http: superfluous response.WriteHeader call from github.com/promhippie/github_exporter/pkg/middleware.Timeout.func1.1 (timeout.go:17)`  once every hour (when Prometheus scrap the target)

In prometheus, the scrapes take around 250s
![image](https://github.com/promhippie/github_exporter/assets/34195850/7a58b248-5ca8-46a4-aca8-69672be14de4)

And the metrics are getting stale because I scrape less than every 5m
![image](https://github.com/promhippie/github_exporter/assets/34195850/09abcecd-b56c-4f37-86c1-224e803f14a3)

I can get the data if I use the `max_over_time[2d]` function to access older values, but this doesn't look like a good idea because the older workflows dissapear over time
![image](https://github.com/promhippie/github_exporter/assets/34195850/1f5eaecc-f2e0-42b8-9899-8af7c9c093dc)

Do you have any idea?
