### ISSUE TITLE
Admin stats on NON enterprise account?

### ISSUE THREAD

**Issue by luciano-buono** [promhippie/github_exporter#249]
Hi, I enabled the flag `GITHUB_EXPORTER_COLLECTOR_ADMIN` with the idea of collecting the metrics related to the admin stats (available to ORG aswell). 
However, the exporter seems to make the api call as:

```json
{"collector":"admin","err":"GET https://api.github.com/enterprise/stats/all: 404 Not Found []","level":"error","msg":"Failed to fetch admin stats","ts":"2023-08-31T14:46:37.877816288Z"}
```

Is it possible to have the ADMIN stats in a not enterprise account?

**Comment by tboerger** [comment]
Currently it's not possible, I didn't even realized that these starts could be available for orgs as well. Sounds like a great feature of the stats are not already part of the org metrics.

**Comment by luciano-buono** [comment]
Noted! Thanks for the confirmation


Sorry to use this issue for another topic, but I'm having a problem with the WORKFLOW collector.

I have enabled the flag  `GITHUB_EXPORTER_COLLECTOR_WORKFLOWS: true`  and defined multiple repos (which many have a workflow history), however I don't see any metrics about that.

The pod has been running for 17h so it already should have gathered info about it. (Also there are not ERROR logs about anything


Also in a strange note, in the metrics I see this:
```
# HELP github_request_failures_total Total number of failed requests to the api per collector.
# TYPE github_request_failures_total counter
github_request_failures_total{collector="action"} 0
github_request_failures_total{collector="billing"} 0
github_request_failures_total{collector="org"} 0 
```

And I havent enabled the actions collector, but I enabled the workflow collector.. Here are my env vars defined in the helm chart:

```yaml
extraEnvVariables:
  GITHUB_EXPORTER_ORGS: XX
  GITHUB_EXPORTER_REPOS: XX

  GITHUB_EXPORTER_COLLECTOR_BILLING: true

  # This admin stats are only for enterprise accounts
  GITHUB_EXPORTER_COLLECTOR_ADMIN: false
  # Not needed
  GITHUB_EXPORTER_COLLECTOR_REPOS: false

  # Information about orgs and repos runners. If they are busy or idle
  GITHUB_EXPORTER_COLLECTOR_RUNNERS: false
  
  # Check timeouts
  GITHUB_EXPORTER_COLLECTOR_WORKFLOWS: true
  # Needed to avoid context deadline exceeded errors in collector
  GITHUB_EXPORTER_REQUEST_TIMEOUT: 5m
  GITHUB_EXPORTER_PER_PAGE: 100
  GITHUB_EXPORTER_WEB_TIMEOUT: 3m

  GITHUB_EXPORTER_WEB_PPROF: true
```

**Comment by tboerger** [comment]
On the start of the exporter you should see a log line if the workflow exporter is enabled, after that you should be able to see recent workflow metrics of enabled repos.

**Comment by kirillbilchenko** [comment]
@luciano-buono I facing the same issue, not clear how to make this working

**Comment by luciano-buono** [comment]
Which issue do u mean? the GITHUB_EXPORTER_COLLECTOR_ADMIN is not possible currently.

For the workflows metrics, it's sorta working for me, I needed to add repos with current workflows runs.
The collector looks like it request information from the last workflow run, not a list with previous runs.

**Comment by kirillbilchenko** [comment]
@luciano-buono seems like I figured out, when I added GITHUB_EXPORTER_ORGS: xxx and GITHUB_EXPORTER_COLLECTOR_WORKFLOWS: I was expecting that it will export all the workflows from the org, but it the end to make it working, I added GITHUB_EXPORTER_REPO: org/* and now exporter is working

**Comment by luciano-buono** [comment]
@kirillbilchenko How many repos do u have?  

What values did you put in:
```yaml
  GITHUB_EXPORTER_REQUEST_TIMEOUT: 10m
  GITHUB_EXPORTER_PER_PAGE: 100
  GITHUB_EXPORTER_WEB_TIMEOUT: 10m
```

I'm getting a lot of Rate limiting by Github and can't figure out the right values
