### ISSUE TITLE
Deployed as a K8s helm chart, pod is being throttled with no apparent reason

### ISSUE THREAD

**Issue by luciano-buono** [promhippie/github_exporter#493]
Hi, I have deployed the app using the Helm chart: https://github.com/promhippie/charts/tree/master/stable/github-exporter and set the following resources block:

```yaml
      resources:
        limits:
          cpu: 300m
          memory: 250Mi
        requests:
          cpu: 50m
          memory: 50Mi
```

Checking the CPU usage with ice:

```
➜ k ice cpu
PODNAME                                                 CONTAINER                           USED  REQUEST  LIMIT  %REQ  %LIMIT
prometheus-promhippie-github-exporter-7fdd9fbd9c-2sqkb  github-exporter                     9m    50m      300m   17.03 2.84
```

I see that the reported usage is very low, however I'm facing throttling issues

![Image](https://github.com/user-attachments/assets/c08ad45d-9251-4242-87f5-f1dead981590)

![Image](https://github.com/user-attachments/assets/3c3de2fe-e84b-42f6-8660-3743fb8d1026)

I suspect this may be related to the container trying to burst for very small time, not enough for the metrics to catch it

![Image](https://github.com/user-attachments/assets/e75fa833-238b-49ca-8120-bf7611f8215f)
